### ISSUE TITLE
No ELF library support compiled in.

### ISSUE THREAD

**Issue by xjj210130** [xdp-project/bpf-examples#89]
hi all:
 My env is centos 7. core is 5.15.46 (build by myself) gcc 11.2.1 clang 14.0.6 llvm 14.0.6 bpftool is v5.15.46

I do as following:
1: git clone https://github.com/xdp-project/bpf-examples.git
2: cd bpf-examples/lib and build libbpf libxdp  (libbpf libxdp  i download the new master version)
3: cd bpf-examples/lib/xdp-tools/lib/testing
4: make 
5 : run ip link set dev eno3 xdp obj xdp_pass.o sec xdp
There is wrong message:
 No ELF library support compiled in.

How to solve this probelm. Thanks.
strings /usr/lib64/libstdc++.so.6 | grep GLIBC  GLIBCXX_3.4.30
 
I build os kernel with CONFIG_XDP_SOCKETS.

**Comment by tohojo** [comment]
Well, that's coming from 'ip', so it seems your iproute2 install is
missing elf support. So you'll need to replace it if you want to use it
to load BPF programs. Or, y'know, just run this on a distro that
actually has BPF support out of the box instead of trying to compile
your own kernel on a userspace that doesn't... RHEL8 and RHEL9 both have
support out of the box, so you could just move to CentOS stream.

**Comment by xjj210130** [comment]
Thanks
